apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: actor-worker-scaler
  namespace: local-infra
spec:
  scaleTargetRef:
    name: actor-worker
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: actor-jobs
      messageCount: "5"
      connectionFromEnv: SERVICEBUS_CONNECTION_STRING
